name: likeminds_chat_mm_fl
description: Sample UI package for LikeMinds Chat SDK
version: 1.2.0
homepage: "https://likeminds.community"
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ## Flutter SDK
  flutter:
    sdk: flutter

  ## LikeMinds Chat SDK
  likeminds_chat_fl: 1.2.0
    #path: ../LikeMinds-Flutter-GroupChat-SDK

  ## Flutter Packages
  path: 1.8.3
  sizer: ^2.0.15
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shimmer: ^2.0.0
  fluttertoast: ^8.2.1
  get_it: ^7.2.0
  lazy_load_scrollview: ^1.3.0
  infinite_scroll_pagination: ^3.2.0
  open_filex: ^4.3.2
  permission_handler: ^10.2.0
  simple_s3: ^0.3.2
  shared_preferences: ^2.1.0
  uni_links: ^0.5.1
  visibility_detector: ^0.4.0+2
  url_launcher: ^6.1.7
  go_router: ^6.5.7
  google_fonts: ^4.0.3
  custom_pop_up_menu: ^1.2.4
  device_info_plus: ^8.0.0
  flutter_emoji: ^2.4.0
  video_player: ^2.6.1
  video_thumbnail: ^0.5.3
  cached_network_image: ^3.2.3
  flutter_polls: ^0.1.2
  intl: ^0.18.1
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  overlay_support: 2.1.0
  envied: ^0.3.0
  extended_text_field: ^12.0.0
  equatable:
  flutter_typeahead_mm:
    path: lib/packages/flutter_typeahead-4.3.7
  image_picker: ^0.8.7+4
  file_picker: ^5.2.10
  firebase_database: ^10.1.1
  pdf_render: ^1.3.8
  path_provider: ^2.0.14
  carousel_slider: ^4.2.1
  swipe_to_action: ^0.2.0
  syncfusion_flutter_pdf: ^21.2.10
  syncfusion_flutter_pdfviewer: ^21.2.10
  flutter_svg: ^1.1.6
  flutter_cache_manager: ^3.3.0
  flick_video_player: ^0.5.0
  pdf_bitmaps: ^1.0.1
  emoji_picker_flutter: ^1.6.1
  flutter_portal: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  envied_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/likeminds_chat_mm_fl/assets/icons/doc_pdf.svg
    - packages/likeminds_chat_mm_fl/assets/icons/explore.svg
    - packages/likeminds_chat_mm_fl/assets/icons/notification_check.svg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
